const icons = {
    book: '/image/book.png',
    doc: '/image/docs.png',
    html: '/image/html.png',
    css: '/image/css.png',
    js: '/image/js.png',
    react: '/image/reactjs.png',
    react_native: '/image/react-native.png',
    nodejs: '/image/nodejs.png',
    php: '/image/php.png',
    go: '/image/go.png',
    py: '/image/python.png',
    django: '/image/django.png',
    java: '/image/java.png',
    dart: '/image/dart.png',
    flutter: '/image/flutter.png',
    c_sharp: '/image/c-sharp.png',
    c_plus: '/image/c-plus.png',
    mysql: '/image/mysql.png',
    firebase: '/image/firebase.png',
    mongodb: '/image/mongodb.png',
    postgress : '/image/postgress.png',
    excel: '/image/excel.png',
}
export default icons;